### ISSUE TITLE
doc 的 polygon 跟 polyline 漏寫 id

### ISSUE THREAD

**Issue by bestpika** [essoduke/jQuery-tinyMap#10]
如題，我看文件的時候想說奇怪怎麼 `marker` 有 `id` 可是其他沒有還以為只有 `marker` 可以用 `id` XD

另外問一下，`clear` 使用 `id` 的時候可以只比對 prefix 嗎？
因為我在底下有看到一個 `get` 裡面抓 `id` 有寫一個 `以自訂 ID 方式（此方式將比對符合輸入字串起始的 ID）`

另外要是 `marker`、`polygon`、`polyline` 這些也可以一組一組丟進去就好了...
還有 `markerCluster` 可以針對每組使用

例如
```javascript
$(selector).tinyMap({
    ...
    marker: [{
        id: 'id',
        markers: [{...}, {...}],
        markerCluster: true|false,
        func: ...
    }],
    polygon: [{
        id: 'id',
        polygons:: [{...}, {...}],
        func: ...
    }]
})
```

另外有些範例你昨天更新之後無法顯示變成有錯誤
`jquery.tinyMap-3.3.16.min.js?ver=3.3.16.0:5 Uncaught TypeError: Cannot read property 'png' of undefined`

**Comment by essoduke** [comment]
Q1：
clear 的規則和 get 是一樣的，都可以 Prefix 方式過濾：
[https://jsfiddle.net/nhwheuoc/1/](https://jsfiddle.net/nhwheuoc/1/)

Q2：
圖層以群組方式建立的話可以避免多個 marker（或其他圖層）要共用參數（例如 event）時，必須逐一 assign 的麻煩，但是使用上或許不夠直觀，讓我想一下...XD

Q3：本機測試時沒發現，現在已經修正了，感謝提醒。

**Comment by essoduke** [comment]
Docs 已經加上了「自訂 ID」的參數說明。
