### ISSUE TITLE
關於自我定位和搜尋最近的分店問題

### ISSUE THREAD

**Issue by rosakay** [essoduke/jQuery-tinyMap#11]
您好，小弟是剛入行的新手正在幫公司做分店資訊的網頁會需要用到搜尋最近分店的按鈕，這兩個禮拜已經爬過您的文章，也做得差不多了，目前有成功定位自己的位置，還有用你的計算式算出最近的分店位置並將中心定位過去，但是順序出了點問題，我點下搜尋按鈕後，map都會先定位到我預設的假位置，然後才會算好GPS定好的位置，我得再按一次他才會定位到我要的最近分店，已經換過code的順序了，不是沒效果就是壞掉，想請問有沒有辦法可以讓他先搜尋跟算好我的定位後再去定位最近分店呢？

 以下是我的code：

`var map = $('#map');

var current = ['23.4678812', '120.43860749999999'];  // 假位置

var loc = [{
    addr: ['25.0071463', '121.51574540000001'],
    text: '福和店<br>新北市永和區福和路327號<br>02-29268708<br>09:30AM~10:00PM',
    label: '福和店',
    css: 'labels',
    // 動畫效果
    animation: 'DROP|BOUNCE'
}, {
    addr: ['22.9777598', '120.22095480000007'],
    text: '崇學店<br>台南市東區崇學路18號<br>06-2672988<br>09:30AM~10:00PM',
    label: '崇學店',
    css: 'labels',
    // 自訂圖示
    // 動畫效果
    animation: 'DROP|BOUNCE'
}, {
    addr: ['23.564602', '120.30418699999996'],
    text: '北港店<br>雲林縣北港鎮中山路18號<br>05-7834488<br>09:00AM~06:30PM',
    label: '北港店',
    css: 'labels',
    // 動畫效果
    animation: 'DROP|BOUNCE'
}, {
    addr: current,
    text: '<strong>目前位置</strong>',
    icon: '../Images/web/rabbit_head3.png',
    css: 'label'
}, ];`

`$(function() {

    $(".searchBtn").on("click", function getLocation() {  // 點選按鈕後 定位自己所在位置
        if (navigator.geolocation) {
            navigator.geolocation.getCurrentPosition(showPosition);
        } else {
            alert("Geolocation is not supported by this browser.");
        }

    });

    function showPosition(position) {  // 將current的值改成定位後的座標
        var lat = position.coords.latitude,
            lon = position.coords.longitude;
        console.log(lat + ', ' + lon)
        current[0] = lat;
        current[1] = lon;
    }

    $(function getmap() {

        $('#map').tinyMap({
            center: '25.0071463,121.51574540000001',
            marker: loc,
            zoom: 17,
            event: {
                'idle': {
                    'func': function() {

                // 點選按鈕後搜尋離current的座標最近的座標
                        $(".searchBtn").on("click", function neardyStore() { 
                            var i = 0,
                                icon = {},
                                pos = {},
                                distance = [],
                                nearest = false,

                                // 取得目前位置的 LatLng 物件
                                now = new google.maps.LatLng(current[0], current[1]),
                                // 取得 instance
                                m = $('#map').data('tinyMap'),
                                // 取得已建立的標記
                                markers = m._markers;

                            // 使用迴圈比對標記（忽略最末個）
                            for (i; i < loc.length - 1; i += 1) {
                                // 建立標記的 LatLng 物件
                                pos = new google.maps.LatLng(loc[i].addr[0], loc[i].addr[1]);
                                /**
                                 * 利用幾何圖形庫比對標記與目前位置的測地線直線距離並存入陣列。
                                 * http://goo.gl/ncP2Gz
                                 */
                                distance.push(google.maps.geometry.spherical.computeDistanceBetween(pos, now));
                            }
                            console.dir(distance);

                            // 尋找陣列中最小值的索引值
                            nearest = distance.indexOf(Math.min.apply(Math, distance));
                            if (false !== nearest) {
                                if (undefined !== markers[nearest].infoWindow) {

                                    // 開啟此標記的 infoWindow
                                    markers[nearest].infoWindow.open(m.map, markers[nearest]);

                                    // 更換此標記的圖示
                                    markers[nearest].setIcon('http://app.essoduke.org/tinyMap/6.png');
                                    markers[nearest].infoWindow.content += '<p>距離: ' + distance[nearest].toString() + ' 公尺</p>';

                                    // 移動此標記至地圖中心
                                    m.map.panTo(markers[nearest].position);

                                }
                            }
                        })
                    },
                    'once': true
                }
            }

        });
    });

});`

**Comment by essoduke** [comment]
可以利用 autoLocation 自動記錄裝置目前的位置至元素。
.searchBtn 事件內就只需要取得元素，並轉成需要的格式，再進行計算即可。

請參考範例：
https://jsfiddle.net/cmgw352o/1/

**Comment by rosakay** [comment]
非常不好意思又來打擾你，我剛剛有試著套用你給的範本，出現了些問題，
1. 
你給的第一段
`    $.fn.tinyMapConfigure({
        'libraries': 'geometry'
    });`
看起來好像是幾何圖形程式運算用的碼，
請問我可以用
`<script src="http://maps.google.com/maps/api/js?sensor=false&language=zh-TW&libraries=geometry"></script>`
來替代嗎？

2.我加上你的autoLocation後沒壞掉，接著我把我的getLocation()和showPosition(position)刪掉、然後把整個按鈕事件替換成你的按鈕事件後，一進網頁有自動找到我的位置，可是點了search沒反應，沒有自動幫我跑到最近店家，console裡顯示了“markers[nearest] is undefined“，我沒有自己改東西，所以不知道問題出在哪，不好意思麻煩你解惑。

以下是我現在的碼：
`$(function() {

    $.fn.tinyMapConfigure({
        'libraries': 'geometry'
    });

    var map = $('#map');
    var current = ['23.4678812', '120.43860749999999'];
    var loc = [{
        addr: ['25.0071463', '121.51574540000001'],
        text: '福和店<br>新北市永和區福和路327號<br>02-29268708<br>09:30AM~10:00PM',
        label: '福和店',
        css: 'labels',
        // 動畫效果
        animation: 'DROP|BOUNCE'
    }, {
        addr: ['25.033981', '121.54326900000001'],
        text: '大安店<br>台北市復興南路一段386號<br>02-27050608<br>10:00AM~09:30PM',
        label: '大安店',
        css: 'labels',
        iframe: 'mapmap',
        // 動畫效果
        animation: 'DROP|BOUNCE'
    }, {
        addr: ['25.000205', '121.51976460000003'],
        text: '得和店<br>新北市永和區得和路219號<br>02-29273788<br>10:00AM~10:00PM',
        label: '得和店',
        css: 'labels',
        // 動畫效果
        animation: 'DROP|BOUNCE'
    },  {
        addr: ['23.4801475', '120.4495068'],
        text: '噴水店<br>嘉義市西區文化路151號<br>05-2161688<br>09:30AM~10:00PM',
        label: '噴水店',
        css: 'labels',
        // 動畫效果
        animation: 'DROP|BOUNCE'
    }, {
        addr: ['23.3071747', '120.31549540000003'],
        text: '新營店<br>台南市新營區三民路88-3號<br>06-6337778<br>09:30AM~09:30PM',
        label: '新營店',
        css: 'labels',
        // 動畫效果
        animation: 'DROP|BOUNCE'
    }, {
        addr: ['23.564602', '120.30418699999996'],
        text: '北港店<br>雲林縣北港鎮中山路18號<br>05-7834488<br>09:00AM~06:30PM',
        label: '北港店',
        css: 'labels',
        // 動畫效果
        animation: 'DROP|BOUNCE'
    }, ];

// 執行 tinyMap
    map.tinyMap({
        center: '25.0071463,121.51574540000001',
        marker: loc,
        zoom: 17,
        autoLocation: function(pos) {
            // 將目前位置記錄在元素內，供之後讀取（pos 會根據裝置位置自動更新）
            var loc = [pos.coords.latitude, pos.coords.longitude].join(',');
            $('#pos').text(loc);
        }
    });

    // 按鈕事件
    $(".searchBtn").on("click", function neardyStore() {
        var i = 0,
            icon = {},
            pos = {},
            distance = [],
            nearest = false,
            // 取得目前位置的 LatLng 物件
            coords = '',
            now = {},
            // 取得 instance
            // 取得已建立的標記
            markers = map.tinyMap('get', 'marker'),
            // 取得地圖 instance
            m = map.tinyMap('get', 'map');

        // 從元素取得目前位置
        coords = ($('#pos').text()).split(',');
        // 轉成 google maps position object
        now = new google.maps.LatLng(coords[0], coords[1]);

        // 使用迴圈比對標記
        for (i; i < loc.length - 1; i += 1) {
            // 建立標記的 LatLng 物件
            pos = new google.maps.LatLng(loc[i].addr[0], loc[i].addr[1]);
            /**
             * 利用幾何圖形庫比對標記與目前位置的測地線直線距離並存入陣列。
             * http://goo.gl/ncP2Gz
             */
            distance.push(google.maps.geometry.spherical.computeDistanceBetween(pos, now));
        }

        // 尋找陣列中最小值的索引值
        nearest = distance.indexOf(Math.min.apply(Math, distance));
        if (false !== nearest) {
            if ('undefined' !== typeof markers[nearest].infoWindow) {
                // 開啟此標記的 infoWindow
                markers[nearest].infoWindow.open(m, markers[nearest]);
                // 更換此標記的圖示
                markers[nearest].setIcon('https://code.essoduke.org/images/6.png');
                markers[nearest].infoWindow.content += '<p>距離: ' + distance[nearest].toString() + ' 公尺</p>';
                // 移動此標記至地圖中心
                m.panTo(markers[nearest].position);
            }
        }
    })

})();`

**Comment by rosakay** [comment]
還有就是我一開始用你的碼來測試，結果都是壞掉，後來發現是版本太舊（似乎是兩年以前的版本），所以有更新到最新版本的tinymap，可是新版本的插件會導致我的小地圖的選單失效，想請問一下為什麼舊版的反而沒事，新版的會壞掉？

以下是我的選單的碼：
`</script>
function change(value) {

            $('#map').tinyMap('panto', value);
            var storeimg = "";
            var storedata = "";

            if (value == "25.033981,121.54326900000001") { //大安
                storeimg = "url('../Images/web/daan_store.jpg')";
                storedata = "大安店<br>台北市復興南路一段386號<br>02-27050608<br>10:00AM~09:30PM";
            }
            else if (value == "25.0071463,121.51574540000001") { //福和
                storeimg = "url('../Images/web/yonghe_store.jpg')";
                storedata = "福和店<br>新北市永和區福和路327號<br>02-29268708<br>09:30AM~10:00PM";
            } 
            else if (value == "25.000205,121.51976460000003") { //得和
                storeimg = "url('../Images/web/dehe_store.jpg')";
                storedata = "得和店<br>新北市永和區得和路219號<br>02-29273788<br>10:00AM~10:00PM";
            }
            var $storpic = $("div.map_pic");
            $storpic.css("background-image", storeimg);

            var $stordata = $("#stordata");
            $stordata.html(storedata);

        };
</script>`

`<div class="topstyle2 storeSearchBar">
                <select onchange="change(this.options[this.selectedIndex].value)">
                    <option value="#">請選擇</option>
                    <option value="25.033981,121.54326900000001">台北市大安店</option>
                    <option value="25.0071463,121.51574540000001">新北市福和店</option>
                    <option value="25.000205,121.51976460000003">新北市得和店</option>
                   
                </select>
  </div>`

**Comment by essoduke** [comment]
因為不知道你原本使用的版本，所以範例是以最新版本為主。

1.如果是新版 tinyMap 就不需要手動載入 Google Maps API 了。
2.應該是不至於影響到原有的東西才對，請問是否有線上 demo 可以看？

**Comment by rosakay** [comment]
不好意思，因為還沒上架沒有線上demo可以提供，那選單方面我自己試著修復，想問一下我現在是照著你的範例使用，可是為什麼我console裡會顯示“markers[nearest] is undefined“咧？我都沒改範例的碼，只有複製貼上而已，為何你的可以運行我的會undefined咧..

**Comment by essoduke** [comment]
剛剛仔細看了一下，您所謂的選單失效應該是指「地圖無法移動到選單的選取的地點」吧？如果是這樣的話，那就是 `panTo` 大小寫錯了，正確應該是：`$('#map').tinyMap('panTo', value);`

會出現 `markers[nearest] is undefined` 應該就是取不到正確的 marker，可以試著 console.log nearest 和 distance 的內容，看看元素數量符不符合。

**Comment by rosakay** [comment]
真的！居然是大小寫的問題！終於解決這個了，超感謝！

然後剛找到`markers[nearest] is undefined`問題了，因為我沒有`#pos`的`div`所以沒有地方抓座標，等等再研究怎樣不用`#pos`也能抓座標，但又出現了另一個問題，我抓到了`#pos`的值然後跳去最近的分店以後隔不到1秒他會再`panTo`回我的當前位置，我該去哪裡讓他不要一直`panTo`我的當前位置，讓他點一次按鈕就定在最近分店不要再跳回去了

**Comment by essoduke** [comment]
「會自動 panTo 回目前位置」的問題，就必須看到程式碼才能判斷了。方便的話請將這部份的 code 貼上我來看看。

**Comment by rosakay** [comment]
這些是執行地圖的碼和按鈕的碼，我都是用您提供的範本，沒有擅自修改，不知道問題是不是在這裡面
```
// 執行 tinyMap  
            map.tinyMap({
                center: '25.0071463,121.51574540000001',
                marker: loc, 
                zoom: 17,
                autoLocation: function (pos) {
                    // 將目前位置記錄在元素內，供之後讀取（pos 會根據裝置位置自動更新）
                    var loc = [pos.coords.latitude, pos.coords.longitude].join(',');
                    $('#pos').text(loc);
                } 
            });

// 按鈕事件
$(".searchBtn").on("click", function neardyStore() {
        var i = 0,
            icon = {},
            pos = {},
            distance = [],
            nearest = false,
            // 取得目前位置的 LatLng 物件
            coords = '',                            
            now = {},
            // 取得 instance
            // 取得已建立的標記
            markers = map.tinyMap('get', 'marker'),
            // 取得地圖 instance
            m = map.tinyMap('get', 'map');

        // 從元素取得目前位置
        coords = ($('#pos').text()).split(',');
        // 轉成 google maps position object
        now = new google.maps.LatLng(coords[0], coords[1]);                        

        // 使用迴圈比對標記
        for (i; i < loc.length - 1; i += 1) {
            // 建立標記的 LatLng 物件
            pos = new google.maps.LatLng(loc[i].addr[0], loc[i].addr[1]);
            /**
             * 利用幾何圖形庫比對標記與目前位置的測地線直線距離並存入陣列。
             * http://goo.gl/ncP2Gz
             */
            distance.push(google.maps.geometry.spherical.computeDistanceBetween(pos, now));
        }
      
        // 尋找陣列中最小值的索引值
        nearest = distance.indexOf(Math.min.apply(Math, distance));
        if (false !== nearest) {
            if ('undefined' !== typeof markers[nearest].infoWindow) {
                // 開啟此標記的 infoWindow
                markers[nearest].infoWindow.open(m, markers[nearest]);
                // 更換此標記的圖示
                markers[nearest].setIcon('https://code.essoduke.org/images/6.png');
                markers[nearest].infoWindow.content += '<p>距離: ' + distance[nearest].toString() + ' 公尺</p>';
                // 移動此標記至地圖中心
                m.panTo(markers[nearest].position);
            }
        }
    })
```

**Comment by essoduke** [comment]
我測試倒是沒發現問題？
https://code.essoduke.org/demo/tinymap.20160419

※清單部份我是利用 tinyMap 內建的 markerControl 自動產生。

**Comment by rosakay** [comment]
找到問題了，因為未知原因我的chrome不給我定位，所以我一直是用firefox和safari做測試，你提供的範例在firefox和safari也有一直panTo回當前位置的狀況，請問這個兼容性的問題有辦法解決嗎@@?

**Comment by essoduke** [comment]
現在 Chrome 必須要 https 環境才給使用 navigator API 吐位置了... 這我應該沒辦法 XD

會一直 panTo 我猜是因為 autoLocation 預設使用 navigator.watchPositio 之故，所以會一直查詢位置。
或許你可以修改 tinyMap 源碼，將 watchPosition 改為 currentPosition（但是這麼做的話，裝置位置會無法持續更新）

最好的辦法就是，網站直上 SSL....

**Comment by rosakay** [comment]
還是有辦法讓這段code只執行一次嗎？ 因為我不需要他一直持續更新，只是要讓別人知道離自己最近的店是哪一間而已
```
autoLocation: function (pos) {
                    // 將目前位置記錄在元素內，供之後讀取（pos 會根據裝置位置自動更新）
                    var loc = [pos.coords.latitude, pos.coords.longitude].join(',');
                    $('#pos').text(loc);
                }
```

然後我剛有去插件裡面把watchPosition 改為 currentPosition 結果就壞掉了，不知道是不是改錯地方了，但我只找到那裡有watchPosition而已..

**Comment by essoduke** [comment]
我記錯函數名稱了... 是 `getCurrentPosition` 才對 XD

我也修改了一份你可以直接下載使用
https://code.essoduke.org/js/tinyMap/jquery.tinyMap-3.3.19.sp.js

**Comment by rosakay** [comment]
真的是非常感謝你！！大致上完成了，不好意思打擾你這麼久！剩下的小細節我再自己研究一下，感激不盡！
