### ISSUE TITLE
TypeError: a.container.innerHTML is not a function

### ISSUE THREAD

**Issue by cweric** [essoduke/jQuery-tinyMap#14]
TypeError: a.container.innerHTML is not a function

[min]
`a.container.innerHTML(g("<div/>").text(e).html())`

[unmin]
`self.container.innerHTML($('<div/>').text(msg).html());`

innerHTML is HTML DOM property NOT function

**Comment by essoduke** [comment]
感謝指正，已釋出 v3.3.20 修正這項錯誤。

**Comment by cweric** [comment]
Cool, Thanks.
