### ISSUE TITLE
Async API loading timing issue

### ISSUE THREAD

**Issue by ppcat** [essoduke/jQuery-tinyMap#15]
Hi,

When I first time called `$(selector).tinyMap({...})` and it started to download google map api asynchronously. If I called `$(selector).tinyMap('modify', {...})` immediately after first called, the 'modify' may be lost without any information.

The test fiddle is [https://jsfiddle.net/0nmy3x17/2/](https://jsfiddle.net/0nmy3x17/2/)

If the 'modify' called before 'gMapsCallback', it will lost and the modification won't be applied.
```
$(window).on('gMapsCallback', function () {
        self.init();
});
```
Do you have any idea to handle these scenario? Currently I will just load data before I initialize the tinyMap. Thank you!

**Comment by essoduke** [comment]
Maybe you could try to call `modify` in idle event of the map? It should works.
https://jsfiddle.net/e4Lj8jwu/
```javascript
map.tinyMap({
    event: {
        idle: function () {
            map.tinyMap('modify', ...);
        }
    }
});
```
BTW, My chinese is better than english. :)

**Comment by ppcat** [comment]
謝謝！這也是一個解決方法。
