### ISSUE TITLE
Marker with label set content

### ISSUE THREAD

**Issue by ppcat** [essoduke/jQuery-tinyMap#16]
您好，請問 markerWithLabel 要如何設定顯示的文字呢？原本我用 google map api 的寫法如下：
```
var marker = new MarkerWithLabel({
        position: position,
        map: this.map,
        labelContent: "0",
        labelAnchor: new google.maps.Point(20, 38),
        labelClass: "map-labels",
        labelInBackground: false,
        labelStyle: {opacity: 1.0},
        icon: this.createSymbol("#dd4b39")
});
```
用 `labelContent: "0"` 可以設定 marker 內的文字，結果如下圖：
![2016-05-16 5 13 29](https://cloud.githubusercontent.com/assets/776439/15285473/df97c1bc-1b89-11e6-8ba4-8bcef70d3486.png)

現在想要改用 tinyMap 來做 markerWithLabel，原始檔的路徑已失效所以我沒放 fiddle，
```
$.fn.tinyMapConfigure({
        'api': '//maps.google.com/maps/api/js',
        'v': 3,
        'key': 'API_KEY',
        'language': 'zh-TW',
        'withLabel': 'URL_PATH/markerwithlabel.js'
});

var marker = [{
        id: "0",
        addr: position,
        text: "show some text",
        icon: this.createSymbol("#dd4b39"),
        newLabel: "0",
        labelContent: "0",
        labelAnchor: new google.maps.Point(20, 38),
        labelClass: "map-labels",
        labelInBackground: false,
        labelStyle: {opacity: 1.0}
}];
```
顯示結果如下圖：
![2016-05-16 4 59 42](https://cloud.githubusercontent.com/assets/776439/15285041/a001c7a2-1b87-11e6-8a30-fd15969e4412.png)
不知道是否有什麼地方我弄錯了嗎？是想要在 marker 裡面顯示 "0" 而不是用 `newLabel: "0"` 顯示在下面，謝謝！

**Comment by essoduke** [comment]
應該是 Async scope 的問題：建立 marker 時，MarkerWithLabel 尚未載入導致無法作用。

我暫時修改成適用的版本，請先下載這個檔案試試看，之後我會再 push 回去：
https://cdn.essoduke.org/js/tinyMap/jquery.tinyMap-3.3.20.sp.js

範例：
https://code.essoduke.org/demo/tinymap.2016051601

**Comment by ppcat** [comment]
這個版本還是沒辦法作用，但我發現一個方法是在 `modify` 的時候也帶 `markerWithLabel: true` 進去就可以了..本來我只有在第一次 initialize tinyMap 有帶 `markerWithLabel: true` 是沒辦法出現 label 的，整個流程大概變成這樣:
```
map.tinyMap({
    markerWithLabel: true,
    event: {
        idle: {
            func: {
                map.tinyMap('modify', function() {
                    markerWithLabel: true,
                    marker: markers
                });
            }
        },
        once: true
    }
});
```
謝謝！

**Comment by essoduke** [comment]
剛剛釋出了 v3.4.0，一併解決了 modify 無法沿用原始地圖設定的問題，請下載這個版本再試試看。

Example:
```javascript
// Initialize
map.tinyMap({
    'markerWithLabel': true,
    'marker': [...]
});

// Modify 會沿用 map 的參數設定，所以不須再傳入 markerWithLabel
map.tinyMap('modify', {
    'marker': [...]
});
```

**Comment by ppcat** [comment]
感謝快速回覆～我在試 v3.4.0 時發現 idle once 行為怪怪的，他會觸發兩次，第一次地圖載入完成會 idle，任意拖曳或縮放地圖之後會再觸發一次 idle，請問這樣是正常的嗎？
測試: [https://jsfiddle.net/0apoax61/1/](https://jsfiddle.net/0apoax61/1/)

另外 modify 完也會 trigger idle 一次這也是正常行為嗎？這樣的話我要重新思考 idle 的用法來符合我的情境，謝謝。

**Comment by essoduke** [comment]
因為程式內的判斷邏輯有誤造成的問題 :p
剛剛已經修正了，請重新下載 v3.4.0（清除快取）後再試試看。

**Comment by ppcat** [comment]
謝謝，問題已解決 :)
