### ISSUE TITLE
Baidu Maps support

### ISSUE THREAD

**Issue by brettwinters** [essoduke/jQuery-tinyMap#18]
Great plugin - Thanks very much!

I'm trying to get the Baidu API working: "http://api.map.baidu.com/api?v=1.2"

Since I can't speak Chinese, does anyone have any tips on configuring: 

`$.fn.tinyMapConfigure({
    'api': '//api.map.baidu.com/api?v=1.2',
    'language': 'zh-TW',
    'libraries': ????,
    'clusterer': ?????
});`

As a feature request, would it be possible to set/switch the API depending on user's location (in China use BM since GM is blocked)?

**Comment by essoduke** [comment]
I'm so sorry, this plugin is only for Google Maps.
But it would be useful if the plugin can also support the Baidu Map.

I'll try to get the Baidu API key and study it.
Thanks for your opinion. :+1:

**Comment by brettwinters** [comment]
that would be great: There is an example here: [https://github.com/twinh/jquery-baidu-map-picker/blob/master/jquery-baidu-map-picker.js](url)
