### ISSUE TITLE
原生參數問題

### ISSUE THREAD

**Issue by bestpika** [essoduke/jQuery-tinyMap#9]
```javascript
mapTypeControlOptions: {
    style: google.maps.MapTypeControlStyle.DROPDOWN_MENU,
    position: google.maps.ControlPosition.TOP_RIGHT,
}
```
然後一片白之後 console 表示
```
google is not defined
```
請問這該怎解？

**Comment by bestpika** [comment]
...好吧最簡單的作法就是把那幾個參數的值都找出來用

**Comment by bestpika** [comment]
我想了一下，如果可以是先載入 Google Maps 的 API 是不是就可以避免這個問題？
意思就是把 Google Maps API 從 tinyMap 裡面拔出來另外載入
或者是 tinyMap 會偵測是不是已經載入 Google Maps API 了，載入就不會再載入一次

**Comment by bestpika** [comment]
然後我又發現我事先載入真的可以 XD

**Comment by essoduke** [comment]
因為採用 async 載入 Google Maps API 所以會有這個問題，當然 tinyMap 本身會檢查是否已載入 API。不過如果因為這樣讓使用者需要自行載入 API 就失去 v3 的初衷了 XD
當然啦，暫時是必須這樣解...

下一個修正版我會想辦法解決這個問題...

**Comment by essoduke** [comment]
剛剛釋出了 v3.3.16，針對原生參數 Constants 的問題做了修正，以字串傳入常數名稱即可，請試試看：

原始用法：
```javascript
mapTypeControlOptions: {
    style: google.maps.MapTypeControlStyle.DROPDOWN_MENU
}
```
新增語法：
```javascript
mapTypeControlOptions: {
    style: "google.maps.MapTypeControlStyle.DROPDOWN_MENU"
}
```

**Comment by bestpika** [comment]
可以用沒問題，另外我想問一下有沒有可以等待 tinyMap 載入之後再執行的方法 (不是用 idle)?

**Comment by bestpika** [comment]
我發現...
只要先載入 Google Maps 的 API 就什麼問題都沒有了耶...

**Comment by essoduke** [comment]
直接載入 API 肯定是沒問題的，只是... 還得手動插入 script...

不過您問的問題我不太懂，有具體的例子嗎？搞不好可以解決...
> 因為其實我是要填東西進 marker 裡面卻發現在 idle 裡面好像找不到方法填東西進去...

**Comment by bestpika** [comment]
你在 tinyMap 裡面有一個 array 是用來放 markers 的
但是我想從 idle 的 event 裡面去擺東西進 tinyMap 的 markers
可是這時候的 this 是 tinyMap 的 map 所以我不知道要怎麼放進去 XD

**Comment by essoduke** [comment]
可以用 _selector.data('tinyMap');_ 取得 tinyMap instance;

```javascript
map.tinyMap({
    'event': {
        'idle': function () {
            var instance = map.data('tinyMap');
            console.log(instance._markers); // Get `_markers` Array
        }
    }
});
```

**Comment by bestpika** [comment]
咦，我以為在 `idle` 裡面抓不到 `instense` XD

**Comment by bestpika** [comment]
還有個問題，我有些東西想要讓他在 `idle` 裡面只跑一次是要設 `once:true`
可是我同時又有東西要讓他每次 `idle` 都執行要怎麼做 冏
因為我去查 `Events` 裡面沒有另一個類似的 event

**Comment by essoduke** [comment]
我想... 只要設個變數來控制就可以了？

```javascript
// 控制變數
var hasRun = false;

selector.tinyMap({
    ...
    event: {
        idle: function () {
            if (!hasRun) {
                // 只執行一次的區段
                hasRun = true;
            }
            // 每次都執行的區段
        }
    }
```

**Comment by bestpika** [comment]
其實我就是在想有沒有不要用變數控制可以達成的方法 XD...

**Comment by essoduke** [comment]
這個好像沒辦法耶，畢竟只要用變數就能解決的 XD
